### ISSUE TITLE
Array objects matching template

### ISSUE THREAD

**Issue by Paic** [eykrehbein/strest#109]
Is there any way to check if objects of an array match a "template" (see my comment in [#12](https://github.com/eykrehbein/strest/issues/12#issuecomment-420417833)) ?
The current implementation of JsonPath does not seems to be able to fulfill this use case.

**Comment by eykrehbein** [comment]
@jgroom33 is this possible with jsonpath? I'm not really into the jsonpath feature

**Comment by jgroom33** [comment]
I don't think so. Would validating against a json schema work

**Comment by Paic** [comment]
What do you mean by json schema ?  Without using JsonPath ?

**Comment by jgroom33** [comment]
#110

**Comment by Paic** [comment]
It seems it would work for validating array objects, but I think it's a common use case and using an external file to describe those tests would be inconvenient.

**Comment by jgroom33** [comment]
In release 2.0, there are some [proposed changes](https://github.com/eykrehbein/strest/tree/develop#response-validation) to validation.  Adding a new validation type of `jsonschema` would work as follows (just convert the jsonschema to yaml and specify it in the strest.yml):

```yaml
validate:
  jsonpath: path.to.array
  jsonschema:
    type: array
    items:
      type: object
      properties:
        loc:
          type: string
        toll:
          type:
          - string
          - 'null'
        message:
          type:
          - string
          - 'null'
      required:
      - loc
```

**Comment by jgroom33** [comment]
it should even be possible to declare the schemas in the global var section:

```yaml
variables:
  mySchema:
    type: array
    items:
      type: object
      properties:
        loc:
          type: string
        required:
        - loc
requests:
  foo:
    ...
    validate:
      jsonpath: path.to.array
      jsonschema: <$ variables.mySchema $>
```
