### ISSUE TITLE
For Loop

### ISSUE THREAD

**Issue by jgroom33** [eykrehbein/strest#114]
Possible implementation:

```
version: 2

requests:
  call1:
    request:
      url: https://postman-echo.com/time/now
      method: GET
  call2:
    request:
      url: https://jsonplaceholder.typicode.com/posts
      method: POST
      postData:
        mimeType: application/json
        text:
          foo: 2
  repeat_until:
    until:
      jsonpath: call1.content
      expect: <$ Env("STREST_GMT_DATE") $>
      else_goto: call1 # when false
      goto: call3 # when true
  call3:
    request:
      url: https://jsonplaceholder.typicode.com/posts
      method: POST
      postData:
        mimeType: application/json
        text:
          foo: 2
```

**Comment by jgroom33** [comment]
Another possible implementation:

```yml
version: 2

requests:
  call1:
    request:
      url: https://jsonplaceholder.typicode.com/posts
      method: GET
  for_Looper:
    forEach: <$ call1.content $>  # This is an array response from call1
    request:
      url: https://jsonplaceholder.typicode.com/posts/<$ forEach.id $>
      method: GET
```

**Comment by jgroom33** [comment]
third option:

```yml
version: 2

requests:
  call1:
    request:
      url: https://jsonplaceholder.typicode.com/posts
      method: GET
  call1.content.forEach(item):
    request:
      url: https://jsonplaceholder.typicode.com/posts/<$ item.id $>
      method: GET
```
