### ISSUE TITLE
Verify against returned arrays

### ISSUE THREAD

**Issue by betsegaw** [eykrehbein/strest#12]
Say the returned response data has the following format,
```
[
  {
    "id": "5b9763b3ef7c4000018387cd",
    "from": "Bank",
    "to": "Bank",
    "amount": 0,
    "gameID": "SomePreDefiniedValue"
  }
]
```
How do I verify that "gameId" == "SomePreDefiniedValue"?

**Comment by betsegaw** [comment]
Apparently, this works.

```
validate:
      json:
        [0]:
          gameID: 'SomePreDefiniedValue'
```
Is this a hacky way of doing it or is there a proper way to do it?

**Comment by eykhagen** [comment]
@betsegaw
Unfortunately, there is no proper way to handle arrays, *yet*. Do you have any suggestions how to improve this? 🤔

**Comment by Paic** [comment]
I think a good start for handling arrays would be to have the ability to define an item "template" like :

```
validate:
      json:
        [array]:
          name: Type(String)
          age: Type(Number)
          email: Type(String.Email)
```

Each item must match the template for the JSON to be validated.

I don't know if it's implementable but the [Joi ](https://github.com/hapijs/joi)library has very advanced objects validation that would fit a lot of use case. 😄

**Comment by betsegaw** [comment]
P.S I really like the choice of YAML as the description of a test case. Yes, some test cases are very complex and require a lot of setup, but for the most part, 90% of basic verification tests are "check that f(x) = y" types, so having a data only input like this helps simplify the whole thing. So thanks for putting this together!

**Comment by jgroom33** [comment]
What if a joi validator is implemented:

```
version: 1 
requests:
  getStatuses:
    url: http://domain.com/endpoint
    method: POST
    data:
      json: {"foo": "bar"}
    validate:
      joi:
        ?????????
```

I don't know what the syntax beyond joi: would be, but this seems more explicit and potentially could handle more use cases.
