### ISSUE TITLE
Can't pass header value to chained request

### ISSUE THREAD

**Issue by jdm-hexagon** [eykrehbein/strest#122]
**Describe the bug**
Using a chained request, I'm passing a value in the response of the first request, to the next request's header

```text
 Template render error: (unknown path) [Line 6, Column 16]
  attempted to output null or undefined value

Response: 
null
[ Strest ] Failed before finishing all requests
```

**To Reproduce**
```yaml
version: 2

requests:
  login:
    request:
      url: http://localhost/maf/rest/3.0/user/login
      method: POST
      postData:
        mimeType: application/json
        text:
         username: user
         password: word
  tokenNeeded:
    request:
      url: http://localhost/maf/rest/3.0/user/validate
      method: get
      headers:
      - name: x-device-auth
        value: <$ login.content.Result.token $>
```

The Content that gets logged out when using the `-p` switch is:
```text
"﻿{\"Success\":true,\"Errors\":null,\"Result\":{\"token\":\"63635411\",\"account\":{\"guid\":\"159f7e60-dfec-46db-9ffd-498669038b8b\",\"username\":\"user\",\"name\":\"user user\",\"userGroupCode\":\"admin\",\"userGroupDescription\":\"Administrator Group\"}}}"
```

**Expected behavior**
The *tokenNeeded* request should pass as `<$ login.content.Result.token $>` appears to be valid
Specifying a string literal for `x-device-auth` header passes test:
```text
headers:
  - name: x-device-auth
  value: '63635411'
```

**Additional context**
Apologies in advance if this is a configuration error!
