### ISSUE TITLE
Run requests asynchronously

### ISSUE THREAD

**Issue by strix** [eykrehbein/strest#134]
Running all of the requests synchronously takes a lot of time. Running requests asynchronously would be much faster.
I know there's a lot to consider here with what is already in place especially when considering dependent variables from other requests.

I was thinking of these changes to the yaml to accomplish this:

```yml
version: 2 # might require version 3 for this
async: true

requests:
  healthCheck:
    request:
      url: https://foobar.com/health-check
      method: GET
  longRunningRequest:
    request:
      url: https://foobar.com/lots-of-work
      method: GET
  login: # will return { authenticated: true }
    ...
  authNeeded:
    requires: # list of all dependent requests that need to run first (e.g. for variables to be present)
      - login
    request:
    ...
      headers:
      - name: Authorization
        value: Bearer <$ login.content.authenticated $>  # It's possible to use the status code, headers, and status text from previous calls.
  anotherAuthNeeded:
    requires: # list of all dependent requests that need to run first (e.g. for variables to be present)
      - login
    request:
    ...
      headers:
      - name: Authorization
        value: Bearer <$ login.content.authenticated $>  # It's possible to use the status code, headers, and status text from previous calls.
```

In this scenario: 
1. `usersHealth`, `longRunningRequest` and `login` all run/resolve asynchronously.
2. Once `login` returns successfully, `authNeeded` and `anotherAuthNeeded` both run asynchronously. If there are more dependent requests, their names are added to the `requires` list and are only ran once the dependencies have returned successfully.

[listr](https://github.com/SamVerschueren/listr) seems like it would come in handy to accomplish this.
