### ISSUE TITLE
Feature: Response code validation

### ISSUE THREAD

**Issue by eykrehbein** [eykrehbein/strest#34]
Add feature to validate the response status code

```yaml
version: 1

requests:
  test:
    url: https://echo.getpostman.com/status/400
    method: GET
    validate:
      code: 2xx # status code needs to be in range of 200 - 299
```
