### ISSUE TITLE
Validation: Convert XML response to JSON

### ISSUE THREAD

**Issue by eykrehbein** [eykrehbein/strest#52]
If the response's format is XML, convert it into JSON before validation to be able to validate it with the standard JSON syntax.

```yml
validate:
   json:
      ...
```
