### ISSUE TITLE
log_to_file

### ISSUE THREAD

**Issue by jgroom33** [eykrehbein/strest#54]
```yaml
  logger:
    url: foo.com
    method: GET
    log_to_file: true
```

This would result in a file called `logger.json` that contains the output of the request
