### ISSUE TITLE
log_request

### ISSUE THREAD

**Issue by jgroom33** [eykrehbein/strest#55]
```yaml
  my_request:
    url: foo.com
    method: GET
    log_request: true
```

This would result in the request object and resolved uri being logged.  This would be helpful to have a copy of the json and to show the URI with environment vars and values populated.

It might be good to create a log object as:

```yml
  my_request:
    url: foo.com
    method: GET
    log:
      output: true
      file: true
      request: true
```
