### ISSUE TITLE
Output response

### ISSUE THREAD

**Issue by jgroom33** [eykrehbein/strest#57]
Assume 2 files where the goal is to output an env var from the request in file 1 and use it in file 2

File 1:

```yaml
requests:
  test:
    url: https://postman-echo.com/get
    method: GET
    data:
      params:
        foo: bar
    output_env_vars:
      FILE_1_OUTPUT: args.foo
```

output:

```json
{"args":{"foo":"bar"}}
```

```yaml
requests:
  test:
    url: https://postman-echo.com/get
    method: GET
    data:
      params:
        foo: Env(FILE_1_OUTPUT)
```

**Comment by jgroom33** [comment]
Alternative implementation:
Assuming file output from #55 

```yaml
requests:
  file1_test1:
    url: https://postman-echo.com/get
    method: GET
    data:
      params:
        foo: bar
    log:
      file: true
```

```yaml
requests:
  file2:
    url: https://postman-echo.com/get
    method: GET
    data:
      params:
        foo: Json(file1_test1.args.foo)
```
