### ISSUE TITLE
Extract from array if

### ISSUE THREAD

**Issue by jgroom33** [eykrehbein/strest#59]
Assume a request returns:

```json
[ {"foo":1, "bar": 1},  {"foo":2, "bar": 2} ]
```
It would be beneficial to extract the value of key `bar` given a value for foo.

This is typically handled in code using loops or find functions.

**Comment by jgroom33** [comment]
Potential implementations or workarounds (assuming that modifying the request URL is not possible) :
1. Add a new yaml function: Eval()
2. Add a node library like lodash, jq, or jinja and expose as a new yaml function: _() or Jq()
3. Post process in cli (using jq or other) after log.file.true

**Comment by jgroom33** [comment]
JSONPath seems to be a good option: https://github.com/dchester/jsonpath#jpvalueobj-pathexpression-newvalue

This works:
`$.phoneNumbers[?(@.type=="iPhone")].number`
using:
http://jsonpath.com/

**Comment by jgroom33** [comment]
Presumed implementation `JsonPath()`:

```yml
version: 1

requests:
  todoOne:
    url: https://jsonplaceholder.typicode.com/posts
    method: POST
    data:
      json:
        myArray:
        - foo: 1
           bar: 1
        - foo: 2
           bar: winner winner chicken dinner
  todoTwo:
    url: https://jsonplaceholder.typicode.com/posts
    method: POST
    data:
      json:
       baz: JsonPath(todoOne.$.myArray[?(@.foo==2)].bar
```
