### ISSUE TITLE
Improved response validation

### ISSUE THREAD

**Issue by palsivertsen** [eykrehbein/strest#6]
Thanks for this nice tool!

When writing tests it's also important to test failures, e.g. making sure that submitting invalid credentials does not give an auth token. It would be nice if you could do more advanced assertions on the response like so:

```yaml
requests:
  login: # a successful login
    url: http://localhost:8080/auth
    method: POST
    body:
      json:
        username: alice
        password: secret
    response:
      code: [200-300) # expect a response code in range 200 (inclusive) to 300 (exlusive)
      body: 
        type: Base64
  login using params:
    url: http://localhost:8080/auth
    method: POST
    params:
      username: alice
      password: secret
    response:
      code: [200-300) # expect a response code in range 200 (inclusive) to 300 (exlusive)
      body:
        type: Base64
  login wrong password:
    url: http://localhost:8080/auth
    method: POST
    body:
      json:
        username: alice
        password: 123
    response:
      code: [400-500) # expect a response code in range 400 (inclusive) to 500 (exlusive)
      body:
        json:
          error: wrong username or password
```
