### ISSUE TITLE
WIP: validate pointer

### ISSUE THREAD

**Issue by jgroom33** [eykrehbein/strest#63]
Support this:

```yml
version: 1

requests:
  todoOne:
    url: https://jsonplaceholder.typicode.com/posts
    method: POST
    data:
      json:
        myArray:
        - foo: 1
          bar: 1
        - foo: 2
          bar: 2
    validate:
      jsonpath:
        myArray.1.foo: 2
```
