### ISSUE TITLE
Feature: Basic Auth

### ISSUE THREAD

**Issue by jgroom33** [eykrehbein/strest#65]
support this:

```yml
version: 1

requests:
  login:
    url: https://postman-echo.com/basic-auth
    Auth:
        basic:
            username: postman
            password: password
    method: GET
```

This would result is a header:
      Authorization: Basic cG9zdG1hbjpwYXNzd29yZA==
