### ISSUE TITLE
Define Environment

### ISSUE THREAD

**Issue by jgroom33** [eykrehbein/strest#66]
This would allow the defined env vars to be stored in an initial test file.

```yml
version: 1
environment:
  STREST_URL: https://jsonplaceholder.typicode.com
requests:
  environment:
    url: Env(STREST_URL)/todos/1
    method: GET
```
