### ISSUE TITLE
Feature: setNextRequest

### ISSUE THREAD

**Issue by jgroom33** [eykrehbein/strest#67]
Postman provides this capability:
https://www.getpostman.com/docs/v6/postman/collection_runs/building_workflows

Typically, this is used after a response param is evaluated

**Comment by jgroom33** [comment]
Possible implementation:

```yml
version: 1

requests:
  todoOne:
    url: https://jsonplaceholder.typicode.com/posts
    method: POST
    data:
      json:
        foo: 1
  todoTwo:
    if:
      operator: Value(todoOne.skip)
      value: 2
    url: https://jsonplaceholder.typicode.com/todos/2
    method: GET
```

Only the first request above would execute.  `todoTwo` should create a logging event as skipped
