### ISSUE TITLE
Feature: Set execution order

### ISSUE THREAD

**Issue by eykrehbein** [eykrehbein/strest#69]
Option to add a parameter in each test file which defines in which order the files should be executed.

```yml
# File 1
version: 1
order: 1 # will be executed first
requests:
   ... 
```
```yml
# File 2
version: 1
order: 2 # will be executed after file 1
requests:
   ... 
```
