### ISSUE TITLE
Filename()

### ISSUE THREAD

**Issue by jgroom33** [eykrehbein/strest#95]
Assume the filename is `postman-echo.strest.yml`

Access the filename in the request:
```yml
version: 1                            # only version at the moment

requests:                             # all test requests will be listed here
  testRequest:                        # name the request however you want
    url: https://Filename().com/get  # required
    method: GET                       # required
```
